{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .source.targetRevision }}
    path: {{ .source.path }}
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: {{ .destination.server }}
    namespace: {{ .destination.namespace }}
  syncPolicy:
    automated:
      prune: {{ .syncPolicy.automated.prune }}
      selfHeal: {{ .syncPolicy.automated.selfHeal }}
    syncOptions:
      {{- range .syncPolicy.syncOptions }}
      - {{ . }}
      {{- end }}
{{- end }}
